### PR TITLE
PDS4 Information Model Release 1.21.0.0

### PR DESCRIPTION
**Pull request by pds-ops**
Automated tagging of repo for nominal release of sub-model for PDS4 Release 1.21.0.0

### CODE REVIEW

**Comment by jordanpadams** [comment]
@rsjoyner it looks like we have a couple updates needed:

* looks like one of the valid test cases has a bug
* looks like we never addressed this comment: https://github.com/pds-data-dictionaries/ldd-proc/pull/29#discussion_r1380873270

can we update that on this branch?

**Review by rsjoyner — APPROVED** [review]
Based on the most changes, I guess I approve

**Review by rsjoyner — APPROVED** [review]
Again, this file needs to be deleted.  I edited in a valid value.  But, this test case is redundant

**Review by rsjoyner — APPROVED** [review]
Based on changes, I approve

**Comment by jordanpadams** [comment]
@rsjoyner as the steward for this LDD, if you approve, you can just merge this.

**Comment by rsjoyner** [comment]
Ta da...

**Pull request merged**
